import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import { Header } from '@/components/navbar';
import './globals.css';

const roboto = Roboto({ subsets: ['latin'], weight: ['400','500','700'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={roboto.className}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
